// 24 Elder Futhark Kapsamlı Mitolojik Hikaye, Aşk ve Kariyer Kehanet Kütüphanesi

export type RuneDetailContent = {
  story: string;
  loveUpright: string;
  loveReversed: string;
  careerUpright: string;
  careerReversed: string;
  keywords: string[];
};

export const RUNE_DETAILED_INSIGHTS: Record<string, RuneDetailContent> = {
  fehu: {
    story: "Nordik mitolojisinde Fehu, bereket tanrıçası Freyja'nın altın ışıltısını ve ilk evrensel ateşi temsil eder. Kadim Vikingler için altın ve sığır gibi somut serveti, paylaşıldıkça çoğalan kadersel bereketi simgeler.",
    loveUpright: "İlişkide karşılıklı değer görme, güven hissi ve duygusal zenginlik. Birlikte kurulan hayaller somut ve kalıcı bir yuvaya dönüşür.",
    loveReversed: "Aşkta maddi hesaplar, güvensizlik veya partnerden aşırı beklenti yüzünden doğan kıskançlık ve sürtüşmeler.",
    careerUpright: "Verilen emeklerin finansal karşılığı, yeni gelir kapıları, başarılı yatırımlar ve iş yerinde hak edilen itibar.",
    careerReversed: "Gereksiz harcamalar, geciken ödemeler veya kariyerde açgözlülük yüzünden yapılabilecek hatalar.",
    keywords: ["Maddi Bereket", "Freyja'nın Altını", "Kazanım", "Güven"],
  },
  uruz: {
    story: "Nesli tükenmiş kudretli yaban öküzü 'Aurochs'un vahşi ve eğilmez gücünü taşır. Genç Viking savaşçılarının erginlenme töreninde tek başına avladığı bu kutsal güç, saf yaşam enerjisini simgeler.",
    loveUpright: "Yüksek cinsel çekim, derin tutku ve partneri koruma arzusu. İlişkiyi sarsan sorunları sevgiyle aşacak sarsılmaz güç.",
    loveReversed: "İlişkide baskıcı tavırlar, aşırı inatçılık veya öfke patlamalarının getirdiği geçici kopukluk.",
    careerUpright: "Zorlu projeleri tek başına sırtlayıp başarıya ulaştırma, fiziksel ve zihinsel dayanıklılık, liderlik.",
    careerReversed: "Aşırı çalışma sonucu tükenmişlik, motivasyon kaybı veya esneklik gösterememekten kaynaklanan tıkanıklık.",
    keywords: ["Yaşam Gücü", "Vahşi İrade", "Şifa", "Dayanıklılık"],
  },
  thurisaz: {
    story: "Gök gürültüsü tanrısı Thor'un devleri dize getirdiği efsanevi çekici Mjölnir ve koruyucu dikenin rünüdür. Kaos güçlerine karşı aşılmaz bir kalkan oluşturur.",
    loveUpright: "İlişkiyi dış etkenlerden ve dedikodulardan koruyan güçlü bağ. Kırılma noktasından sonra gelen derin arınma.",
    loveReversed: "Öfkeyle söylenen kırıcı sözler, fevri kararlar ve gereksiz savunma mekanizmalarının aşka zarar vermesi.",
    careerUpright: "Rakipleri saf dışı bırakma, kritik kararlarda kararlılık ve kriz anlarında soğukkanlılıkla zafere ulaşma.",
    careerReversed: "Düşünmeden atılan adımların yaratacağı hukuki veya ticari riskler; sakin kalıp beklemek gerekir.",
    keywords: ["Thor'un Çekici", "Koruma Kalkanı", "Kritik Eşik", "Savunma"],
  },
  ansuz: {
    story: "Baş Tanrı Odin'in ilahi nefesi ve sözün kutsal büyüsüdür. Şiir balı Kvasir'in bilgeliğini ve evrendeki tüm işaretlerin fısıltısını taşır.",
    loveUpright: "Ruhsal düzeyde derin sohbetler, kalpten kalbe kurulan açık ve dürüst iletişim, geleceğe dair ortak vizyon.",
    loveReversed: "Gizlenen sırlar, yanlış anlaşılmalar, dedikodu veya partnerin sözlerine güvenmekte zorlanma.",
    careerUpright: "Mülakatlarda, sunumlarda ve ikna süreçlerinde muazzam başarı; bilge bir akıl hocasından gelen kilit tavsiye.",
    careerReversed: "Eksik bilgiyle hareket etme, sahte vaatler veya iletişim kazaları yüzünden aksayan işler.",
    keywords: ["Odin'in Nefesi", "İlahi Söz", "Bilgelik", "Doğru İletişim"],
  },
  raidho: {
    story: "Güneş arabasının gökyüzündeki kadersel rotasını ve kozmik düzeni (Rád) temsil eder. Vikinglerin deniz aşırı seferlerindeki pusulası ve ruhun tekamül yolculuğudur.",
    loveUpright: "İlişkide aynı yöne doğru ahenkle yürüme, ortak seyahatler ve ilişkinin doğal, rahat bir ritme oturması.",
    loveReversed: "İletişimde ritim kaybı, ayrı düşme, ortak planların ertelenmesi veya taraflardan birinin uzaklaşma hissi.",
    careerUpright: "İş seyahatleri, kariyer rotasında doğru yönü bulma, tıkalı bürokratik süreçlerin hızla çözülmesi.",
    careerReversed: "Planların son anda değişmesi, yolculukta aksilikler veya adaletsiz hissettiren çalışma koşulları.",
    keywords: ["Kozmik Rota", "Seyahat", "Ahenk", "Doğru Ritim"],
  },
  kenaz: {
    story: "Demircilerin ocağındaki yaratıcı ateş ve karanlık mağarayı aydınlatan çam meşalesidir. Bilginin ve sanatın karanlığı yırtan aydınlatıcı gücüdür.",
    loveUpright: "Kalpleri ısıtan yoğun tutku, romantik jestler ve ilişkide saklı kalmış güzelliklerin coşkuyla açığa çıkması.",
    loveReversed: "Tutkunun kıskançlık veya takıntıya dönüşmesi, aradaki ateşin soğuması ya da hayal kırıklığı.",
    careerUpright: "Parlak ve yaratıcı fikirler, problem çözme dehası, yeni projelerin ışıldaması ve dikkat çekme.",
    careerReversed: "Yaratıcı tıkanıklık, enerjinin tükenmesi veya yeteneklerin yeterince takdir görmemesi hissi.",
    keywords: ["Yaratıcı Meşale", "Aşk Ateşi", "Aydınlanma", "İlham"],
  },
  gebo: {
    story: "Tanrılar ile insanlar arasındaki kutsal armağanlaşma yasasını simgeler. 'Her hediye bir karşılık ve bağ talep eder' ilkesiyle gerçek ruhsal eşitliği temsil eder.",
    loveUpright: "Ruh ikizi uyumu, alma-verme dengesinin mükemmelliği, koşulsuz sevgi ve kadersel evlilik/birlik.",
    loveReversed: "Gebo simetriktir; ancak tek taraflı fedakarlıklar veya bağımlılık ilişkisi konusunda uyarıda bulunur.",
    careerUpright: "Her iki taraf için de kazançlı ortaklıklar, adil sözleşmeler ve cömert destekçiler bulma.",
    careerReversed: "Gebo simetriktir; sözleşmelerde ve ortaklıklarda sınırları net çizmek gerektiğini hatırlatır.",
    keywords: ["Kutsal Hediye", "Eşit Birlik", "Ruh Eşi", "Denge"],
  },
  wunjo: {
    story: "Klanın zafer sancağı ve kardeşlik sofrasındaki saf sevinçtir. Acı ve çilenin ardından gelen kadersel huzur ve tatmini simgeler.",
    loveUpright: "Aşkta en yüksek mutluluk, evlilik teklifi, geçmiş küslüklerin tatlıya bağlanması ve kalpte hafiflik.",
    loveReversed: "Geçici heveslerin getirdiği hayal kırıklığı, anlaşılmama hissi veya arkadaşların ilişkiye müdahalesi.",
    careerUpright: "Beklenen başarının kutlanması, iş arkadaşlarıyla tam uyum ve terfiyle taçlanan bir dönem.",
    careerReversed: "İş yerinde uyumsuzluk, ertelenen kutlamalar veya başarıyı paylaşmakta yaşanan zorluklar.",
    keywords: ["Zafer Sevinci", "Kalp Huzuru", "Kutlama", "Murat"],
  },
  hagalaz: {
    story: "Evrenin dokuz diyarını sarsan kozmik dolu fırtınasıdır. Eski, çürümüş yapıları kökünden söküp yerini bereketli arınmış toprağa bırakır.",
    loveUpright: "İlişkideki yapay dengeleri yıkan ani kriz, ancak ardından gelen sarsılmaz gerçeklik ve arınma.",
    loveReversed: "Hagalaz simetriktir; değişime inatla direnmenin sadece acıyı uzatacağını fısıldar.",
    careerUpright: "Kontrol dışı ani krizlerin ardından gelen zorunlu ama çok daha hayırlı yeni bir kariyer yönü.",
    careerReversed: "Hagalaz simetriktir; eskiyen iş modelini terk etme zamanının geldiğini işaret eder.",
    keywords: ["Kozmik Fırtına", "Arınma", "Kaçınılmaz Değişim", "Kökten Yenilenme"],
  },
  nauthiz: {
    story: "Karanlık ve dondurucu gecede iki tahtayı birbirine sürterek çıkarılan 'ihtiyaç ateşi'dir. Zorluğun içinde saklı olan büyük iradeyi temsil eder.",
    loveUpright: "Zor zamanlardan geçen bir aşkın sabırla kenetlenmesi; yokluğun ve özlemin sevgiyi olgunlaştırması.",
    loveReversed: "Duygusal açlık, partneri boğacak derecede ilgi ihtiyacı veya kendi kuruntularıyla aşkı yıpratma.",
    careerUpright: "Kısıtlı bütçeyle büyük başarılar yaratma, sabır sınavını geçme ve kriz yönetiminde ustalaşma.",
    careerReversed: "Aceleci borçlanmalar, plansız harcamalar veya sabırsızlık yüzünden fırsatları heba etme.",
    keywords: ["İhtiyaç Ateşi", "Sabır Sınavı", "Dayanıklılık", "İrade"],
  },
  isa: {
    story: "Niflheim'ın ezeli ve ebedi buzuludur. Her şeyi dondurarak zamanı durdurur; fırtınanın ortasında mutlak dinginlik sağlar.",
    loveUpright: "Duyguların dinlenmeye çekildiği bekleme dönemi; acele etmeden ilişkinin iç dinamiklerini gözlemleme.",
    loveReversed: "Isa simetriktir; soğukluk ve mesafenin kalıcı olmaması için duyguları ifade etmeyi öğütler.",
    careerUpright: "Stratejik bekleme, yeni adım atmak yerine mevcut durumu koruma ve enerjiyi içeride biriktirme.",
    careerReversed: "Isa simetriktir; donmuş süreçleri zorla çözmeye çalışmanın riskine dikkat çeker.",
    keywords: ["Kutsal Buz", "Duraklama", "Dinginlik", "İçsel Odak"],
  },
  jera: {
    story: "Toprağa ekilen tohumun dört mevsim boyunca büyümesi ve zamanı geldiğinde verilen bol hasattır. Doğanın adaletli döngüsüdür.",
    loveUpright: "Aylardır verilen sevginin ve sabrın karşılık bulması; olgun, sağlam ve mutlu bir beraberlik.",
    loveReversed: "Jera simetriktir; emek vermeden sevgi beklemenin boş bir hayal olduğunu hatırlatır.",
    careerUpright: "Uzun vadeli projelerin başarıyla tamamlanması, maddi kazanç ve hak edilen zafer hasadı.",
    careerReversed: "Jera simetriktir; acele etmeden mevsimin olgunlaşmasını beklemeyi öğütler.",
    keywords: ["Bereketli Hasat", "Kozmik Döngü", "Adalet", "Emek Karşılığı"],
  },
  eihwaz: {
    story: "Dokuz diyarı birbirine bağlayan kutsal porsuk ağacı Yggdrasil'in ölümsüz kökleridir. Yaşam ve ölüm arasındaki köprüdür.",
    loveUpright: "Zamanın yıpratamadığı köklü bir bağ, krizlerin ardından gelen manevi yakınlaşma ve sadakat.",
    loveReversed: "Eihwaz simetriktir; geçmiş kırgınlıkları serbest bırakmanın ilişkiyi kurtaracağını söyler.",
    careerUpright: "Kariyerde köklü ve sarsılmaz bir pozisyon elde etme, krizleri avantaja çevirme gücü.",
    careerReversed: "Eihwaz simetriktir; zorluklar karşısında esnek kalarak dimdik durmayı öğütler.",
    keywords: ["Yggdrasil Ağacı", "Dönüşüm", "Ölümsüz Kökler", "Manevi Köprü"],
  },
  perthro: {
    story: "Nornların (Kader Tanrıçaları) kader zarlarını attığı gizemli fincandır. Henüz yazılmamış geleceğin ve kadınsal sezginin sırrıdır.",
    loveUpright: "Aşkta beklenmedik kadersel sürprizler, gizli bir hayranın açılması ya da sezgilerin haklı çıkması.",
    loveReversed: "Aşkta hayal kırıklığı yaratan sırlar, güven sarsıcı durumlar veya gereksiz kıskançlık oyunları.",
    careerUpright: "Beklenmedik kadersel bir fırsat kapısı, şans oyunlarında ya da spekülatif adımlarda sezgisel başarı.",
    careerReversed: "Gereksiz finansal riskler, gizli kapaklı işlerin ayağa dolanması.",
    keywords: ["Kader Zarı", "Gizli Sır", "Dişil Sezgi", "Kadersel Şans"],
  },
  algiz: {
    story: "Kutsal geyik Heimdallr'ın koruyucu boynuzları ve göksel sığınaktır. Tanrıların koruma kalkanını simgeler.",
    loveUpright: "İlişkiyi koruyan ilahi şefkat ve sevgi zırhı; kötü enerjilerden arınmış huzurlu bir beraberlik.",
    loveReversed: "Savunmasız hissetme, manipülatif insanlara sınır çizememekten doğan duygusal yıpranma.",
    careerUpright: "İş yerinde pozisyonunu sağlama alma, güvenilir müttefikler ve risklere karşı tam koruma.",
    careerReversed: "Sözleşmelerde dikkatli olmama, uyarılara kulak asmama sonucu yaşanabilecek kayıplar.",
    keywords: ["İlahi Koruma", "Geyik Boynuzu", "Sezgisel Radar", "Sığınak"],
  },
  sowilo: {
    story: "Karanlık Nordik kışını yırtan Güneş tanrıçası Sol'un tekeridir. Mutlak zaferin, canlılığın ve berraklığın ışığıdır.",
    loveUpright: "Aşkta tüm şüphelerin dağılması, coşkulu bir sevgi patlaması ve partnerle birlikte parıldama.",
    loveReversed: "Sowilo simetriktir; aşırı ego ve benmerkezci tavırların ilişkiyi yakabileceği uyarısını yapar.",
    careerUpright: "Zirveye ulaşma, liderlik, tam takdir görme ve hedeflere tereddütsüz ulaşma.",
    careerReversed: "Sowilo simetriktir; başarı sarhoşluğuna kapılmadan tevazuyu korumayı öğütler.",
    keywords: ["Güneş Işığı", "Mutlak Zafer", "Canlılık", "Berraklık"],
  },
  tiwaz: {
    story: "Adalet ve savaş tanrısı Tyr'ın onur kılıcıdır. Fenrir'i bağlamak için elini feda eden Tyr gibi dürüstlük ve fedakarlıkla kazanılan zaferdir.",
    loveUpright: "Aşkta dürüstlük, sadakat, partner için mücadele etme cesareti ve sağlam temelli bir bağ.",
    loveReversed: "İlişkide mücadeleyi bırakma, haksızlığa uğrama hissi ya da gurur yüzünden yaşanan kopuş.",
    careerUpright: "Hukuki davalarda ve rekabette haklı zafer, güçlü liderlik ve adil terfi.",
    careerReversed: "Haksız rekabet, motivasyon kaybı veya adil olmayan çalışma şartları.",
    keywords: ["Tyr'ın Kılıcı", "Onur & Adalet", "Cesur Zafer", "Sadakat"],
  },
  berkano: {
    story: "Ana tanrıça Frigg'in kutsal huş ağacıdır. Yeniden doğuşu, annelik şefkatini ve baharın canlandırıcı enerjisini taşır.",
    loveUpright: "Yeni bir aşkın doğuşu, evlilik, bebek müjdesi ve hane içinde sevgi dolu huzurlu bir atmosfer.",
    loveReversed: "Aile içi anlaşmazlıklar, aşırı korumacı tavırların yarattığı boğulma hissi veya geciken planlar.",
    careerUpright: "Yeni bir girişimin başarıyla filizlenmesi, yaratıcı projelerde büyüme ve güvenli kazanç.",
    careerReversed: "Projelerin olgunlaşmadan piyasaya sürülmesi veya ortaklar arasında yaşanan uyumsuzluk.",
    keywords: ["Huş Ağacı", "Yeni Doğuş", "Şefkat & Yuva", "Filizlenme"],
  },
  ehwaz: {
    story: "Odin'in sekiz bacaklı kutsal atı Sleipnir ve savaşçının sadık atıdır. İki canlının mükemmel güvenle oluşturduğu ortaklığı simgeler.",
    loveUpright: "Gözü kapalı güven duyulan bir partner, birlikte taşınma/ev kurma ve hızlı duygusal ilerleme.",
    loveReversed: "Güven sarsılması, partnerle farklı yönlere bakma veya iletişimdeki uyumsuzluklar.",
    careerUpright: "Güçlü bir ortakla hızla yükselme, şehir/iş değişikliği ve kariyerde büyük sıçrama.",
    careerReversed: "Yarı yolda bırakan ortaklar, aksayan seyahatler veya iş yerinde güven eksikliği.",
    keywords: ["Kutsal Yoldaş", "Hızlı İlerleme", "Sarsılmaz Güven", "Uyum"],
  },
  mannaz: {
    story: "İnsanlığın evrensel bilincini ve Heimdallr'ın kurduğu toplumsal düzeni simgeler. 'İnsan insanın aynasıdır' bilgeliğidir.",
    loveUpright: "Derin dostluğa dayanan aşk, birbirini her haliyle kabul etme ve ortak sosyal çevre mutluluğu.",
    loveReversed: "Yalnızlık hissi, yabancılaşma veya partneri kusurları üzerinden yargılama eğilimi.",
    careerUpright: "Ekip çalışmasında mükemmel başarı, mentorluk alma ve toplumsal fayda sağlayan projeler.",
    careerReversed: "İş yerinde entrikalar, dışlanma hissi veya ekip içinde yaşanan ego çatışmaları.",
    keywords: ["İnsan Bilinci", "Ayna", "Dostluk & Birlik", "Sosyal Güç"],
  },
  laguz: {
    story: "Okyanusların derin gizemini ve bilinçaltının engin sularını yöneten tanrı Njord'un rünüdür. Duyguların saf akışıdır.",
    loveUpright: "Ruhsal telepatik çekim, yoğun duygusal yakınlık, rüyalar yoluyla gelen aşk işaretleri.",
    loveReversed: "Duygusal fırtınalarda kaybolma, kuruntular, gerçekleri göremeyecek kadar kapılma.",
    careerUpright: "Sanatsal ve sezgisel mesleklerde zirve, akışa güvenerek doğru fırsatları çekme gücü.",
    careerReversed: "Belirsizlikler içinde yüzme, yanıltıcı vaatlere kanma ve finansal dalgalanmalar.",
    keywords: ["Bilinçaltı Suları", "Derin Sezgi", "Duygusal Akış", "Şifa"],
  },
  ingwaz: {
    story: "Toprak ve bereket tanrısı Frey'in kutsal tohumudur. Kuluçka dönemini tamamlayan gücün patlayarak yeni bir çağı başlatmasıdır.",
    loveUpright: "Birbirine kenetlenmiş olgun bir aşk, evlilik ve meyvesini veren derin bağlılık.",
    loveReversed: "Ingwaz simetriktir; enerjiyi dağıtmadan içsel hazırlığı tamamlamayı öğütler.",
    careerUpright: "Büyük bir projenin başarıyla tamamlanması, yeni bir kariyer fazına geçiş ve büyük kazanç.",
    careerReversed: "Ingwaz simetriktir; tohumun çatlaması için sabırla kuluçkada kalmayı hatırlatır.",
    keywords: ["Kutsal Tohum", "Tamamlanma", "Frey'in Bereketi", "Olgunluk"],
  },
  dagaz: {
    story: "Karanlık gecenin ardında göğü yırtan altın şafak vaktidir. Radikal aydınlanmanın ve kadersel dönüşümün rünüdür.",
    loveUpright: "İlişkideki tüm belirsizliklerin ve krizlerin aniden çözülmesi, aydınlık ve taze bir başlangıç.",
    loveReversed: "Dagaz simetriktir; ışığın gelişini kabul edip eski karanlığa veda etmeyi söyler.",
    careerUpright: "Kariyerde mucizevi bir sıçrama, tıkanıklıkların son bulması ve net başarı vizyonu.",
    careerReversed: "Dagaz simetriktir; yeni dönemin getirdiği fırsatları korkmadan kucaklamayı öğütler.",
    keywords: ["Şafak Vakti", "Radikal Uyanış", "Aydınlık Çözüm", "Dönüşüm"],
  },
  othala: {
    story: "Atalardan kalan kutsal toprakları, miras bilgeliğini ve ailenin koruyucu sınırlarını simgeler.",
    loveUpright: "Geleneksel ve sağlam bir yuva kurma, ailelerin onayladığı kalıcı ve huzurlu bir evlilik.",
    loveReversed: "Miras veya aile baskısı yüzünden ilişkide yaşanan gerilimler, eski kalıplara takılı kalma.",
    careerUpright: "Kalıcı gayrimenkul yatırımları, aile şirketi başarısı ve uzun vadeli maddi güvence.",
    careerReversed: "Miras anlaşmazlıkları, mülk alım-satımında pürüzler veya köhnemiş yöntemlerde ısrar etme.",
    keywords: ["Ata Mirası", "Kutsal Toprak", "Kalıcı Yuva", "Kökler"],
  },
};
