import type { ImageSourcePropType } from 'react-native';

export type FortuneTheme = {
  key: string;
  splashTitle: string;
  splashSubtitle: string;
  accentColor: string;
  figure?: ImageSourcePropType;
  background?: ImageSourcePropType;
  resultBg: ImageSourcePropType;
};

export const FORTUNE_THEMES: Record<string, FortuneTheme> = {
  coffee: {
    key: 'coffee',
    splashTitle: 'Kahve Falı',
    splashSubtitle: 'Osmanlı Saray Kehaneti Başlıyor...',
    accentColor: '#B45309',
    figure: require('@/assets/themes/figures/coffee.png'),
    background: require('@/assets/themes/backgrounds/coffee.jpg'),
    resultBg: require('@/assets/themes/results/coffee.jpg'),
  },
  bakla: {
    key: 'bakla',
    splashTitle: '41 Bakla Falı',
    splashSubtitle: 'Kadim Ocak Remil ve Nazar Kehaneti',
    accentColor: '#0EA5E9',
    figure: require('@/assets/themes/figures/bakla.png'),
    background: require('@/assets/themes/backgrounds/bakla.jpg'),
    resultBg: require('@/assets/themes/results/bakla.jpg'),
  },
  face: {
    key: 'face',
    splashTitle: 'Yüz Falı',
    splashSubtitle: 'Kadim Sima ve Çin Çehre İlmi',
    accentColor: '#E11D48',
    figure: require('@/assets/themes/figures/face.png'),
    background: require('@/assets/themes/backgrounds/face.jpg'),
    resultBg: require('@/assets/themes/results/face.jpg'),
  },
  iching: {
    key: 'iching',
    splashTitle: 'Çin I Ching Falı',
    splashSubtitle: '3000 Yıllık Taoist Değişimler Kitabı',
    accentColor: '#E11D48',
    figure: require('@/assets/themes/figures/iching.png'),
    background: require('@/assets/themes/backgrounds/iching.jpg'),
    resultBg: require('@/assets/themes/results/iching.jpg'),
  },
  rune: {
    key: 'rune',
    splashTitle: 'Nordik Rün Falı',
    splashSubtitle: 'Vikinglerin Kutsal 24 Taşının Bilgeliği',
    accentColor: '#5B8266',
    figure: require('@/assets/themes/figures/rune.png'),
    background: require('@/assets/themes/backgrounds/rune.jpg'),
    resultBg: require('@/assets/themes/results/rune.jpg'),
  },
  celticTree: {
    key: 'celticTree',
    splashTitle: 'Kelt Ağaç Takvimi',
    splashSubtitle: 'Druidlerin Kutsal 13 Ağaç Burcu',
    accentColor: '#4ADE80',
    figure: require('@/assets/themes/figures/celticTree.png'),
    background: require('@/assets/themes/backgrounds/celticTree.jpg'),
    resultBg: require('@/assets/themes/results/celticTree.jpg'),
  },
  palm: {
    key: 'palm',
    splashTitle: 'El Falı',
    splashSubtitle: 'Kader, Akıl ve Kalp Çizgilerinin Sırrı',
    accentColor: '#A855F7',
    figure: require('@/assets/themes/figures/palm.png'),
    background: require('@/assets/themes/backgrounds/palm.jpg'),
    resultBg: require('@/assets/themes/results/palm.jpg'),
  },
  tea: {
    key: 'tea',
    splashTitle: 'Çay Falı',
    splashSubtitle: 'Tasseografi Yaprak ve Kulp Desenleri',
    accentColor: '#10B981',
    figure: require('@/assets/themes/figures/tea.png'),
    background: require('@/assets/themes/backgrounds/tea.jpg'),
    resultBg: require('@/assets/themes/results/tea.jpg'),
  },
  wax: {
    key: 'wax',
    splashTitle: 'Balmumu Falı',
    splashSubtitle: 'Kutsal Alevin ve Erimiş Mumun Dili',
    accentColor: '#F59E0B',
    figure: require('@/assets/themes/figures/wax.png'),
    background: require('@/assets/themes/backgrounds/wax.jpg'),
    resultBg: require('@/assets/themes/results/wax.jpg'),
  },
  scrying: {
    key: 'scrying',
    splashTitle: 'Kara Ayna Durugörü',
    splashSubtitle: 'Obsidyen Aynadaki Ruhsal Vizyon',
    accentColor: '#6366F1',
    figure: require('@/assets/themes/figures/scrying.png'),
    background: require('@/assets/themes/backgrounds/scrying.jpg'),
    resultBg: require('@/assets/themes/results/scrying.jpg'),
  },
  aura: {
    key: 'aura',
    splashTitle: 'Aura & Çakra Falı',
    splashSubtitle: '7 Işıltılı Enerji Merkezi ve Biyo-Aura',
    accentColor: '#EC4899',
    figure: require('@/assets/themes/figures/aura.png'),
    background: require('@/assets/themes/backgrounds/aura.jpg'),
    resultBg: require('@/assets/themes/results/aura.jpg'),
  },
  matrix: {
    key: 'matrix',
    splashTitle: 'Kader Matrisi',
    splashSubtitle: '22 Büyük Arkana ve Sekizgen Kozmik Haritan',
    accentColor: '#8B5CF6',
    figure: require('@/assets/themes/figures/matrix.png'),
    background: require('@/assets/themes/backgrounds/matrix.jpg'),
    resultBg: require('@/assets/themes/results/matrix.jpg'),
  },
  dream: {
    key: 'dream',
    splashTitle: 'Rüya Yorumlama',
    splashSubtitle: 'Bilinçaltının Gizemli Semboller Alemi',
    accentColor: '#8B7CF6',
    figure: require('@/assets/themes/figures/dream.png'),
    background: require('@/assets/themes/backgrounds/dream.jpg'),
    resultBg: require('@/assets/themes/results/dream.jpg'),
  },
  tarot: {
    key: 'tarot',
    splashTitle: 'Tarot Falı',
    splashSubtitle: '78 Kadim Kart ve Evrensel Arketip Açılımı',
    accentColor: '#F59E0B',
    figure: require('@/assets/themes/figures/tarot.png'),
    background: require('@/assets/themes/backgrounds/tarot.jpg'),
    resultBg: require('@/assets/themes/results/tarot.jpg'),
  },
  katina: {
    key: 'katina',
    splashTitle: 'Katina Aşk Falı',
    splashSubtitle: 'Deste-i Katina 65 Kartlık İlişki Açılımı',
    accentColor: '#F43F5E',
    figure: require('@/assets/themes/figures/katina.png'),
    background: require('@/assets/themes/backgrounds/katina.jpg'),
    resultBg: require('@/assets/themes/results/katina.jpg'),
  },
  solitaire: {
    key: 'solitaire',
    splashTitle: 'İskambil Falı',
    splashSubtitle: '32 Kartlık Klasik Fransız Kader Açılımı',
    accentColor: '#10B981',
    figure: require('@/assets/themes/figures/solitaire.png'),
    background: require('@/assets/themes/backgrounds/solitaire.jpg'),
    resultBg: require('@/assets/themes/results/solitaire.jpg'),
  },
  daisy: {
    key: 'daisy',
    splashTitle: 'Papatya Falı',
    splashSubtitle: 'Kutsal Çiçeğin Seviyor / Sevmiyor Sırrı',
    accentColor: '#FBBF24',
    figure: require('@/assets/themes/figures/daisy.png'),
    background: require('@/assets/themes/backgrounds/daisy.jpg'),
    resultBg: require('@/assets/themes/results/daisy.jpg'),
  },
  dice: {
    key: 'dice',
    splashTitle: 'Zar Falı',
    splashSubtitle: '3 Kutsal Zarın Kombinasyon Kehaneti',
    accentColor: '#F59E0B',
    figure: require('@/assets/themes/figures/dice.png'),
    background: require('@/assets/themes/backgrounds/dice.jpg'),
    resultBg: require('@/assets/themes/results/dice.jpg'),
  },
  voiceReading: {
    key: 'voiceReading',
    splashTitle: 'Sesli Fal',
    splashSubtitle: 'Ses Frekansın ve Mistik Yorumlama',
    accentColor: '#06B6D4',
    background: require('@/assets/themes/backgrounds/voiceReading.jpg'),
    resultBg: require('@/assets/themes/results/voiceReading.jpg'),
  },
};
