import type { ImageSourcePropType } from 'react-native';

export const LENORMAND_IMAGES: Record<number, ImageSourcePropType> = {
  1: require('./lenormand_01.png'),
  2: require('./lenormand_02.png'),
  3: require('./lenormand_03.png'),
  4: require('./lenormand_04.png'),
  5: require('./lenormand_05.png'),
  6: require('./lenormand_06.png'),
  7: require('./lenormand_07.png'),
  8: require('./lenormand_08.png'),
  9: require('./lenormand_09.png'),
  10: require('./lenormand_10.png'),
  11: require('./lenormand_11.png'),
  12: require('./lenormand_12.png'),
  13: require('./lenormand_13.png'),
  14: require('./lenormand_14.png'),
  15: require('./lenormand_15.png'),
  16: require('./lenormand_16.png'),
  17: require('./lenormand_17.png'),
  18: require('./lenormand_18.png'),
  19: require('./lenormand_19.png'),
  20: require('./lenormand_20.png'),
  21: require('./lenormand_21.png'),
  22: require('./lenormand_22.png'),
  23: require('./lenormand_23.png'),
  24: require('./lenormand_24.png'),
  25: require('./lenormand_25.png'),
  26: require('./lenormand_26.png'),
  27: require('./lenormand_27.png'),
  28: require('./lenormand_28.png'),
  29: require('./lenormand_29.png'),
  30: require('./lenormand_30.png'),
  31: require('./lenormand_31.png'),
  32: require('./lenormand_32.png'),
  33: require('./lenormand_33.png'),
  34: require('./lenormand_34.png'),
  35: require('./lenormand_35.png'),
  36: require('./lenormand_36.png'),
};

export const LENORMAND_CARD_NAMES: Record<number, { tr: string; suit: string }> = {
  1: { tr: 'Süvari', suit: 'Kupa 9' },
  2: { tr: 'Yonca', suit: 'Karo 6' },
  3: { tr: 'Gemi', suit: 'Maça 10' },
  4: { tr: 'Ev', suit: 'Kupa Papazı' },
  5: { tr: 'Ağaç', suit: 'Kupa 7' },
  6: { tr: 'Bulutlar', suit: 'Sinek Papazı' },
  7: { tr: 'Yılan', suit: 'Sinek Kızı' },
  8: { tr: 'Tabut', suit: 'Karo 9' },
  9: { tr: 'Çiçekler', suit: 'Maça Kızı' },
  10: { tr: 'Tırpan', suit: 'Karo Valesi' },
  11: { tr: 'Kırbaç', suit: 'Sinek Valesi' },
  12: { tr: 'Kuşlar', suit: 'Karo 7' },
  13: { tr: 'Çocuk', suit: 'Maça Valesi' },
  14: { tr: 'Tilki', suit: 'Sinek 9' },
  15: { tr: 'Ayı', suit: 'Sinek 10' },
  16: { tr: 'Yıldızlar', suit: 'Kupa 6' },
  17: { tr: 'Leylek', suit: 'Kupa Kızı' },
  18: { tr: 'Köpek', suit: 'Kupa 10' },
  19: { tr: 'Kule', suit: 'Maça 6' },
  20: { tr: 'Bahçe', suit: 'Maça 8' },
  21: { tr: 'Dağ', suit: 'Sinek 8' },
  22: { tr: 'Yol Çatalları', suit: 'Karo Kızı' },
  23: { tr: 'Fareler', suit: 'Sinek 7' },
  24: { tr: 'Kalp', suit: 'Kupa Valesi' },
  25: { tr: 'Yüzük', suit: 'Sinek Ası' },
  26: { tr: 'Kitap', suit: 'Karo 10' },
  27: { tr: 'Mektup', suit: 'Maça 7' },
  28: { tr: 'Erkek (Anima)', suit: 'Kupa Ası' },
  29: { tr: 'Kadın (Animus)', suit: 'Maça Ası' },
  30: { tr: 'Zambak', suit: 'Maça Papazı' },
  31: { tr: 'Güneş', suit: 'Karo Ası' },
  32: { tr: 'Ay', suit: 'Kupa 8' },
  33: { tr: 'Anahtar', suit: 'Karo 8' },
  34: { tr: 'Balık', suit: 'Karo Papazı' },
  35: { tr: 'Çapa', suit: 'Maça 9' },
  36: { tr: 'Haç', suit: 'Sinek 6' },
};
